version: '3.9'
services:
  db:
    image: mongo
    container_name: regroup-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=marcus
      - MONGO_INITDB_ROOT_PASSWORD=secret